name: robustpointclouds
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.6
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - opencv
  - pip
  - shapely
  - pip:
    - -r requirements.txt